substitutions:
  _PROJECT_ID: "mila-pocs" # Default value, can be overridden at runtime
  _API_SERVICE_NAME: "backend-api"

steps:
  # Build the FastAPI API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$_PROJECT_ID/$_API_SERVICE_NAME:latest'
      - '-f'
      - 'src/backend/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$_PROJECT_ID/$_API_SERVICE_NAME:latest'
