services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      QDRANT_HOST: "${QDRANT_HOST}"
      QDRANT_PORT: "${QDRANT_PORT}"
      API_KEY: ${API_KEY}
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    # Only expose qdrant via docker network:
    expose:
      - "${QDRANT_PORT}"
    # Map port on host to port on docker network:
    # ports:
    #   - "${QDRANT_PORT}:${QDRANT_PORT}"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
